## Loconotion Site Configuration File ##
# full .toml configuration example file to showcase all of Loconotion's available settings
# check out https://github.com/toml-lang/toml for more info on the toml format

# name of the folder that the site will be generated in
name = "about"

# the notion.so page to being parsing from. This page will become the index.html
# of the generated site, and loconotation will parse all sub-pages present on the page
page = "https://www.notion.so/haiyangshi/Haiyang-Shi-3e379ea6738d4cc38cbef0031eda7db2"

## Global Site Settings ##
# this [site] table defines override settings for the whole site
# later on we will see how to define settings for a single page
[site]
  ## Custom Meta Tags ##
  # defined as an array of tables (double square brackets)
  # each key in the table maps to an atttribute in the tag
  # the following adds the tag <meta name="title" content="Loconotion Test Site"/>
  [[site.meta]]
  name = "author"
  content = "Haiyang Shi"
  [[site.meta]]
  name = "title"
  content = "Haiyang Shi, CSE PhD @ OSU"
  [[site.meta]]
  name = "description"
  content = "Haiyang's homepage"

  ## Custom Fonts ##
  # you can specify the name of a google font to use on the site - use the font embed name
  # if in doubt select a style on fonts.google.com and navigate to the "embed" tag to 
  # check the name under CSS rules
  # the following table keys controls the font of specific elements:
  #   site: changes the font for the whole page (apart from code blocks) 
  #         but the settings below override it
  #   navbar: site breadcrumbs on the top-left of the page
  #   title: page title (under the icon)
  #   h1: heading blocks, and inline databases' titles
  #   h2: sub-heading blocks
  #   h3: sub-sub-heading blocks
  #   body: non-heading text on the page
  #   code: text inside code blocks
  [site.fonts]
  site = 'Nunito'
  navbar = ''
  title = 'Montserrat'
  h1 = 'Montserrat'
  h2 = 'Montserrat'
  h3 = 'Montserrat'
  body = ''
  code = ''

  ## Custom Element Injection ##
  # defined as an array of tables [[site.inject]], followed by 'head' or 'body' to set 
  # the injection point, followed by name of the tag to inject
  # each key in the table maps to an atttribute in the tag
  # e.g. the following injects this tag in the <head>:
  #   <link href="favicon-16x16.png" rel="icon" sizes="16x16" type="image/png"/> 
  [[site.inject.head.link]]
  rel="icon" 
  sizes="16x16"
  type="image/png"
  href="/assets/images/FAVICON-IMAGE-16x16"
  [[site.inject.head.link]]
  rel="icon" 
  sizes="32x32"
  type="image/png"
  href="/assets/images/FAVICON-IMAGE-32x32"
  [[site.inject.head.link]]
  rel="icon" 
  sizes="96x96"
  type="image/png"
  href="/assets/images/FAVICON-IMAGE-96x96"
  [[site.inject.head.link]]
  rel="icon" 
  sizes="160x160"
  type="image/png"
  href="/assets/images/FAVICON-IMAGE-160x160"
  [[site.inject.head.link]]
  rel="icon" 
  sizes="196x196"
  type="image/png"
  href="/assets/images/FAVICON-IMAGE-196x196"
  
  # the following injects this tag in the in the <body>:
  #   <script src="custom-script.js" type="text/javascript"></script>
  # note that all href / src files are copied to the root of the site folder 
  # regardless of their original path
  [[site.inject.body.script]]
  type="text/javascript"
  src="//www.google-analytics.com/analytics.js"
  [[site.inject.body.script]]
  type="text/javascript"
  src="/assets/js/gg-analytics.js"

## Individual Page Settings ##
# the [pages] table defines override settings for individual pages, by defining 
# a sub-table named after the page url (or part of the url, but careful about
# not using a string that appears in multiple page urls)
[pages]
  # # the following settings will only apply to this page: 
  # #   https://www.notion.so/d2fa06f244e64f66880bb0491f58223d
  # [pages.d2fa06f244e64f66880bb0491f58223d]
  #   ## custom slugs ##
  #   # inside page settings, you can change the url for that page with the 'slug' key
  #   # e.g. page "/d2fa06f244e64f66880bb0491f58223d" will now map to "/games-list"
  #   slug = "games-list"

  #   # change the description meta tag for this page only
  #   [[pages.d2fa06f244e64f66880bb0491f58223d.meta]] 
  #   name = "description"
  #   content = "A fullscreen list database page, now with a pretty slug"

  #   # change the body font for the list page only
  #   [pages.d2fa06f244e64f66880bb0491f58223d.fonts]
  #   body = 'DM Mono' 

  # # set up pretty slugs for the other database pages
  # [pages.54dab6011e604430a21dc477cb8e4e3a]
  #   slug = "film-gallery"
